name: Setup Postgres
inputs:
  postgres-version:
    description: The Postgres version to download (if necessary) and use
  config:
    description: Set config
  database:
    description: Database to create
  dev-files:
    description: Install development files
  postgis:
    description: Install PostGIS extension (Linux Ubuntu only)
runs:
  using: node20
  main: index.js
