name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12]
        postgres-version: [15]
    steps:
    - uses: actions/checkout@v3
    - uses: ./.
      with:
        postgres-version: ${{ matrix.postgres-version }}
        config: |
          shared_preload_libraries = 'pg_stat_statements'
        database: testdb
    - run: createdb testdb2
    - run: psql -d testdb -c 'SHOW server_version'
    - run: psql -d testdb -h localhost -c 'SHOW server_version'
    - run: psql --version
    - run: pg_config
