name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04, macos-11.0, macos-10.15]
        postgres-version: [13, 12, 11, 10, 9.6]
        include:
        - os: windows-2019
          postgres-version: 13
        - os: windows-2016
          postgres-version: 13
        - os: ubuntu-20.04
          postgres-version: 14
    steps:
    - uses: actions/checkout@v2
    - uses: ./.
      with:
        postgres-version: ${{ matrix.postgres-version }}
        config: |
          shared_preload_libraries = 'pg_stat_statements'
        database: testdb
    - run: createdb testdb2
    - run: psql -d testdb -c 'SHOW server_version'
    - run: psql -d testdb -h localhost -c 'SHOW server_version'
    - run: psql --version
    - run: pg_config
