name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        postgres-version: [13]
    steps:
    - uses: ankane/setup-postgres@credentials
      with:
        postgres-version: ${{ matrix.postgres-version }}
        config: |
          shared_preload_libraries = 'pg_stat_statements'
    - run: psql --version
    - run: psql -c 'SHOW server_version'
    - run: psql postgres://runner@localhost:5432/runner -c 'SHOW server_version'
    - run: createdb testdb
    - run: pg_config
